# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
        - npm i
        - npm run build
  post_build:
    commands:
        - aws s3 sync ./build s3://www.jlinstallers.com
        - aws cloudfront create-invalidation --distribution-id E3PM6PSYNOP1P1
